;;;; @ Auto Insert
(setq-default auto-insert-directory "~/.emacs.d/template/")
(setq-default auto-insert-query nil)
(define-auto-insert "\\.html\\'" "init.html")
(define-auto-insert "\\.css\\'"  "init.css")
(define-auto-insert "\\.jade\\'" "init.jade")
(define-auto-insert "\\.tex\\'"  "init.tex")
(define-auto-insert "\\.c\\'"    "init.c")
(define-auto-insert "\\.cpp\\'"  "init.cpp")
(define-auto-insert "Makefile"   "init.makefile")
(define-auto-insert "\\.py\\'"   "init.py")
(define-auto-insert "\\.rb\\'"   "init.rb")
(define-auto-insert "\\.pl\\'"   "init.pl")
(define-auto-insert "\\.el\\'"   "init.el")
(add-hook 'find-file-hooks 'auto-insert)